#!/usr/bin/env php
<?php

use Configuration\Config;
use CoolCLI\CoolCLI;

require_once 'vendor/autoload.php';

$commandNamespace = Config::get('app.CommandNamespace');
$commandDirectory = __DIR__ . Config::get('app.CommandDirectory');

CoolCLI::registerAllCommands($commandNamespace, $commandDirectory);

$command    = $argv[1] ?? null;
$argument   = $argv[2] ?? null;
$option     = $argv[3] ?? null;

CoolCLI::run($command, $argument, $option);